CSV_SAVE_PATH: "./results/BDD100K_TRAIN_YOLO_KNN_results.csv"

CONTROLLER:
    WEIFHTS_DIR_PATH: './weights'
    WEIFHTS_FILE_PATH: 'weights/controller.ckpt'
    NUM_LAYERS: 1             # number of layers of the state space
    MAX_TRIALS: 300           # maximum number of models generated
    EXPLORATION: 0.8          # high exploration for the first 20 steps
    REGULARIZATION: 1e-3      # regularization strength
    CONTROLLER_CELLS: 60      # number of cells in RNN controller
    EMBEDDING_DIM: 20         # dimension of the embeddings for each state
    RESTORE_CONTROLLER: True  # restore controller to continue training
    EXPLORATION_DIS_FACTOR: 0.99


MANAGER:
    ACCURACY_BETA: 0.8           # beta value for the moving average of the accuracy
    CLIP_REWARDS: 0.0            # clip rewards in the [-0.05, 0.05] range

    DATASET:
      CLASS_NAME_FILE: "./data/BDD100K/class.names"
      IS_DETECTRON: False
      EVAL_FILE: "./data/BDD100K/BDD100K_eval.pkl"
      DETECTRON_GT_FILE: ""
      DETECTRON_EVAL_FILE: ""

    CLASSIDX:
      TRUTH: [0, 1, 2]
      PRED: [2, 5, 7]


MATCHER:
    TYPE: "KnnMatcher"
    SCENE_FILE: "./data/BDD100K/BDD100K_scene.txt"
    BATCH_NUM: 10
    SCENE_SCOPE: [6, 3, 6, 65, 23, 53, 16, 10, 23, 63]
    SCENE_INDEX: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


SEARCHSPACE:
    NUM_LAYERS: 10
    LAYER_NAMES: ['road', 'time', 'weather', 'car', 'motor', 'person', 'truck',
                  'bus', 'truncation', 'occlusion'
                  ]
    LAYER_VALUES: [[0, 1, 2, 3, 4, 5, 6],
                   [0, 1, 2, 3],
                   [0, 1, 2, 3, 4, 5, 6],
                   [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65],
                   [0, 6, 12, 18, 23],
                   [0, 9, 18, 27, 36, 45, 53],
                   [0, 4, 8, 12, 16],
                   [0, 2, 4, 6, 8, 10],
                   [0, 4, 8, 12, 16, 20, 23],
                   [0, 9, 18, 27, 36, 45, 54, 63],
                   ]


TRAIN:
    HISTORY_STORE: True
    HISTORY_FILE: 'train_history.csv'
    BUFFER_FILE: 'buffers.txt'

EVAL:
    GT_FLAG: True
    RS_FLAG: True
    GT:
      SAVE_PATH: "./results/GT/GT_BDD100K_TRAIN_YOLO_KNN.csv"
    RS:
      RS_PATH: "./results/IV_results/BDD100K_TRAIN_YOLO_KNN.csv"
      SAVE_PATH: "./results/GT/RS_BDD100K_TRAIN_YOLO_KNN.csv"